account/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("", views.list, name="list"),
    path("create/", views.create, name="create"),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("account.urls")),
    path('todos/', include("todo.urls")),
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Todo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title
        

todo/forms.py
from django import forms
from .models import Todo

class TodoModelForm(forms.ModelForm):
    class Meta:
        model = Todo 
        # fields = '__all__'
        fields = ['title']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("todos:list")
    
    else:
        form = UserCreationForm()
    return render(request,"account/form.html", {"form":form})
    
    
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("todos:list")
    
    else:
        form = AuthenticationForm()
    return render(request,"account/form.html", {"form":form})
    
    
    
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")
    

todo/views.py
from django.shortcuts import render,redirect
from .forms import TodoModelForm
from django.contrib.auth.decorators import login_required
from .models import Todo
# Create your views here.
@login_required
def list(request):
    # todos = Todo.objects.all()
    todos = request.user.todo_set.all()
    return render(request, "todo/list.html",{'todos':todos})
    
    
@login_required
def create(request):
    if request.method == "POST":
        form = TodoModelForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.user = request.user
            todo.save()
            return redirect("todos:list")
            
    else:
        form = TodoModelForm()
    return render(request, "todo/create.html",{"form":form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo</title>
</head>
<body>
    <ul>
        {% if user.is_authenticated %}
            <p>로그인함!</p>
            <p>{{user}}님 안녕하세요!</p>
            <li><a href={% url 'accounts:logout' %}>로그아웃</a></li>
        {% else %}
            <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
            <li><a href="{% url 'accounts:login' %}">로그인</a></li>
        {% endif %}
         <li><a href="{% url 'todos:create' %}">글작성</a></li>
         <li><a href="{% url 'todos:list' %}">글보기</a></li>
        <li></li>
    </ul>
    {% block body_block %}
    {% endblock %}
</body>
</html>

todo/templates/todo/create.html
{% extends 'base.html' %}
{% block body_block %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

todo/templates/todo/list.html
{% extends "base.html" %}
{% block body_block %}
    <h1>여기는 리스트입니다!!!</h1>
    {% for todo in todos %}
        <h3>{{todo.title}}</h3>
        <p>{{todo.user}}</p>
    {% endfor %}
{% endblock %}